# D:\Final-IDP\.streamlit\secrets.toml

[aws]
aws_access_key_id = "AKIASKTRZDZJAEHISGED"
aws_secret_access_key = "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"
region = "us-east-1"

[rds]
host = "finaldatabase-1.ck3u0weu8m1t.us-east-1.rds.amazonaws.com"
port = 5432
database = "postgres"
user = "finalidp"
password = "MySecureIDPPass2026!"